version: "3.7"
services:
  server:
    container_name: server
    build: ./
    ports:
      - "2000:2000"
    networks:
      - n2_overlay
    environment:
      - 'NODE_ENV=production'
      - 'TZ=Asia/Shanghai'
    depends_on:
       - mongo0
    # deploy:
    #   replicas: 1
    #   placement:
    #     constraints: [node.role == manager]
  mongo0:
    # hostname: mongo0
    container_name: mongo0
    image: mongo:latest
    volumes:
        - ./_db/mongo0:/data/db #host_db:container_db
    ports:
      - 27017:27017
    restart: always
    entrypoint: mongod --bind_ip_all --replSet "rs"
    networks:
      - n2_overlay
  mongo1:
    # hostname: mongo1
    container_name: mongo1
    image: mongo:latest
    volumes:
        - ./_db/mongo1:/data/db
    ports:
      - 27018:27017
    restart: always
    entrypoint: mongod --bind_ip_all --replSet "rs"
    networks:
      - n2_overlay
  mongo2:
    # hostname: mongo2
    container_name: mongo2
    image: mongo:latest
    volumes:
        - ./_db/mongo2:/data/db
    ports:
      - 27019:27017
    restart: always
    entrypoint: mongod --bind_ip_all --replSet "rs"
    networks:
      - n2_overlay
networks:
  n2_overlay: